# Generated by Django 3.2.10 on 2021-12-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('codepostal', models.CharField(max_length=100)),
                ('date_command', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_command'],
            },
        ),
    ]
