# Generated by Django 3.2.10 on 2021-12-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='Items',
            field=models.CharField(max_length=5000),
        ),
    ]
