# Generated by Django 3.2.10 on 2021-12-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_command_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='Items',
            field=models.CharField(max_length=5001),
        ),
    ]
