# Generated by Django 3.2.10 on 2021-12-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_command_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='price_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='command',
            name='quantity_total',
            field=models.IntegerField(default=0),
        ),
    ]
