# Generated by Django 3.2.10 on 2021-12-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211223_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='price_total',
            field=models.CharField(max_length=128),
        ),
    ]
